site_name: Reinforcement Learning
site_description: Introduction to reinforcement learning class, given at ISAE-Supaero
site_url: https://supaerodatascience.github.io/reinforcement-learning/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/reinforcement-learning/master/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/reinforcement-learning/master/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience/reinforcement-learning
repo_url: https://github.com/SupaeroDataScience/reinforcement-learning

# TODO: fill this out
nav:
- Overview: index.md
- Introduction to RL: RL0-intro.md
- Markov Decision Processes: RL1-MDP.md
- Solving MDPs: RL2-DP.md
- Evaluating policies: RL3-eval.md
- Model-free control: RL4-control.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
